In [20]:
import numpy as np

# Input data
X = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
# Corresponding target outputs
y = np.array([[0], [1], [1], [0], [0], [1], [1], [0]])

# Initialize parameters (weights and bias)
np.random.seed(0)
weights = np.random.rand(3, 1)  # 3 weights for 3 inputs
bias = np.random.rand(1)

# Define activation function (e.g., sigmoid)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Training loop
epochs = 10000
learning_rate = 0.1
for epoch in range(epochs):
    # Forward propagation
    inputs = X
    # Calculate output
    output = sigmoid(np.dot(inputs, weights) + bias)
    
    # Calculate loss (mean squared error)
    loss = np.mean((y - output) ** 2)
    
    # Backpropagation
    # Compute gradients
    d_output = (y - output) * sigmoid_derivative(output)
    d_weights = np.dot(inputs.T, d_output)
    d_bias = np.sum(d_output)
    
    # Update parameters
    weights += learning_rate * d_weights
    bias += learning_rate * d_bias

    # Print loss every 1000 epochs
    if epoch % 1000 == 0:
        print(f'Epoch: {epoch}, Loss: {loss}')

# Final trained parameters
print("Trained weights:")
print(weights)
print("Trained bias:")
print(bias)

# Test the trained neuron
test_input = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
predicted_output = sigmoid(np.dot(test_input, weights) + bias)
print("Predicted outputs after training:")
print(predicted_output)

Epoch: 0, Loss: 0.3379911920230958
Epoch: 1000, Loss: 0.25000000343358175
Epoch: 2000, Loss: 0.250000000000005
Epoch: 3000, Loss: 0.25
Epoch: 4000, Loss: 0.25
Epoch: 5000, Loss: 0.25
Epoch: 6000, Loss: 0.25
Epoch: 7000, Loss: 0.25
Epoch: 8000, Loss: 0.25
Epoch: 9000, Loss: 0.25
Trained weights:
[[1.64126363e-16]
 [1.63684182e-16]
 [1.64204935e-16]]
Trained bias:
[-3.31788896e-16]
Predicted outputs after training:
[[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]]


In [21]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

   ---------------------------------------- 0.0/377.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/377.1 MB 1.4 MB/s eta 0:04:37
   ---------------------------------------- 0.0/377.1 MB 1.4 MB/s eta 0:04:37
   ---------------------------------------- 0.1/377.1 MB 491.5 kB/s eta 0:12:48
   ---------------------------------------- 0.1/377.1 MB 525.1 kB/s eta 0:11:58
   ---------------------------------------- 0.1/377.1 MB 554.9 kB/s eta 0:11:20
   ---------------------------------------- 0.2/377.1 MB 541.0 kB/s eta 0:11:37
   ---------------------------------------- 0.2/377.1 MB 622.7 kB/s eta 0:10:06
   ---------------------------------------- 0.2/377.1 MB 599.0 kB/s eta 0:10:30
   ---------------------------------------- 0.3/377.1 MB 605.3 kB/s eta 0:10:23
   ---------------------------------------- 0.3/377.1 MB 610.3 kB/s e

In [4]:
import numpy as np
import tensorflow as tf

# Define the Toffoli gate truth table
toffoli_truth_table = np.array([[0, 0, 0],
                                [0, 0, 1],
                                [0, 1, 0],
                                [0, 1, 1],
                                [1, 0, 0],
                                [1, 0, 1],
                                [1, 1, 0],
                                [1, 1, 1]])

# Define the corresponding outputs for the Toffoli gate
toffoli_outputs = np.array([[0],
                            [0],
                            [0],
                            [0],
                            [1],
                            [1],
                            [1],
                            [1]])

# Define the neural network model with standard activation function
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(3,)),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='sigmoid')  # Using sigmoid activation for binary output
])

# Compile the model with standard loss function (mean squared error)
model.compile(optimizer='adam',
              loss='mse',
              metrics=['accuracy'])

# Train the model
model.fit(toffoli_truth_table, toffoli_outputs, epochs=5, batch_size=8, verbose=1)

# Evaluate the model
loss, accuracy = model.evaluate(toffoli_truth_table, toffoli_outputs)
print(f'Loss: {loss}, Accuracy: {accuracy}')

# Test the model with some inputs
test_inputs = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1],
                         [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
predictions = model.predict(test_inputs)
predictions = np.round(predictions)  # Round predictions to 0 or 1
print("Predictions:")
print(predictions)


Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.2496
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6250 - loss: 0.2494
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6250 - loss: 0.2492
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6250 - loss: 0.2490
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6250 - loss: 0.2488
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - accuracy: 0.6250 - loss: 0.2486
Loss: 0.24855256080627441, Accuracy: 0.625
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
Predictions:
[[1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 1. 1.]]
